Version Refactor
QuiltMC/quilt-loader pull request #102
Opened 2022-07-25 17:55 UTC by TheGlitch76

This is a full refactor of how Quilt Loader represents Versions, mostly focused on reverting poor decisions (like 3-component semver) and bringing us up-to-date with the newest Fabric APIs (VersionInterval). **Almost all API touched by this PR is a breaking change.**

This PR will allow:
- Better representation of more kinds of versions than the old API
- Error messages during mod solving that can suggest a certain range of versions to install, even with complex dependencies.

Definitely not my cleanest work; reviews + suggestions to improve are welcome

2022-07-28 11:55 UTC, hYdos commented
This is missing the original commits with the original authors no? Why would you leave those out if the code isnt yours? This isnt an attack, its an genuine question?

2022-07-28 14:48 UTC, TheGlitch76 commented
We follow all of our obligations under the Apache 2.0 license to the best of our ability. Preserving commit history is, notably, not one of those obligations.

2022-07-28 21:57 UTC, MartyAlana commented
> We follow all of our obligations under the Apache 2.0 license to the best of our ability. Preserving commit history is, notably, not one of those obligations.

What about not just doing the minimum and instead having enough ethics to allow them to get recognized for writing code which is in your loader?

2022-07-29 08:46 UTC, Leo40Git approved these changes
LGTM!

2022-08-23 14:46 UTC, AlexIIL commented on src/test/java/org/quiltmc/test/VersionComparisonTests.java
> +//	}
Did these tests fail, or do they need re-doing?

2022-08-23 14:47 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/DependencyOverrides.java
> -}
Why was this class deleted? (Or was it moved but I just missed where it went)

2022-08-23 14:50 UTC, AlexIIL requested changes
This looks good, except for dependency override code being removed?

2022-11-05 23:45 UTC, AlexIIL commented
Merged (with major edits) in #117

2022-11-05 23:45 UTC, closed without merging