Remove v0 mod metadata and the things surrounding it
QuiltMC/quilt-loader pull request #30
Opened 2021-06-20 21:41 UTC by TheGlitch76

Upstream broke everything that would use v0 mod metadata by migrating the impl details of loader to a different package.
We may as well remove this technical debt now.

This PR is a precursor to some incoming Loader Plugin-style abstractions to mod loading, which are needed to make the QMJ stuff not a complete mess.

2021-07-20 01:46 UTC, Platymemo requested changes

2021-07-20 01:46 UTC, Platymemo commented on src/main/java/org/quiltmc/loader/impl/metadata/ModMetadataParser.java
>  					+ "\nPlease update fabric-loader to be able to read this.", schemaVersion));
```suggestion
					+ "\nPlease update Quilt Loader to be able to read this.", schemaVersion));
```

2021-07-20 01:52 UTC, AlexIIL reviewed
Personally I'm not very happy to see backwards compatibility be removed from loader, since loader is meant to work on all versions (old and new), unlike QSL.

However this functionality would need to be re-implemented anyway in a fabric-compat plugin, and that can by done by copying the relavent code directly from fabric-loader, so I don't think removing this from here is a bad idea.

As a sidenote, this *isn't technical debt*, since none of this code is really limiting our ability to make changes. (As we need to keep FMJ v1 around, and the code for handling v1 is already most of the way there towards handling v0 as well).

2021-07-20 20:48 UTC, Leo40Git approved these changes
goodbye old code, we knew ye well :pensive:

2021-07-21 01:22 UTC, Siuolthepic approved these changes
I support removal of v0 mod metadata.

BTW, will this bump us a version? Because with some of the more recent commits it would be really nice to see this in the maven.

2022-05-09 00:42 UTC, closed without merging