Support sided mixin configs
QuiltMC/quilt-loader pull request #395
Opened 2024-01-09 06:38 UTC by OroArmor

2024-01-09 10:31 UTC, AlexIIL requested changes
This needs to be an [RFC](https://github.com/QuiltMC/rfcs/blob/main/specification/0002-quilt.mod.json.md#the-environment-field) before we can merge this unfortunately. (I've considered writing an RFC to move the spec to this repo instead, but for now this change needs to be there too).

2024-01-09 10:31 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/V1ModMetadataReader.java
> +					destination.computeIfAbsent(EnvType.valueOf(environment.asString().toUpperCase()), (env) -> new ArrayList<>()).add(config.asString());
Two problems:

- `Enum.valueOf` throws an exception if the passed name isn't a valid enum constant, but this should use `parseException()` or use an alternative test (a custom switch?)
- This should accept only the same names as the existing environment field: https://github.com/QuiltMC/rfcs/blob/main/specification/0002-quilt.mod.json.md#the-environment-field.

2024-01-09 10:31 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/V1ModMetadataReader.java
> +				LoaderValue environment = object.get("environment");
You need to test if `environment` is a `LoaderValue.LType.STRING` or not before converting it to one. (Since `LoaderValue.asString()` throws a `ClassCastException` if it's not a string, which doesn't contain any information about what part of the json isn't a string).

2024-01-09 10:31 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/V1ModMetadataReader.java
> +				LoaderValue config = object.get("config");
You need to test if `environment` is a `LoaderValue.LType.STRING` or not before converting it to one. (Since `LoaderValue.asString()` throws a `ClassCastException` if it's not a string, which doesn't contain any information about what part of the json isn't a string)

2024-01-17 18:39 UTC, OroArmor commented
Rfc has been merged!

2024-01-17 19:13 UTC, AlexIIL approved these changes

2024-01-17 19:42 UTC, merged