Begin QMJ Writer
QuiltMC/quilt-loader pull request #446
Opened 2024-08-08 06:27 UTC by OroArmor

This will allow people to make tools to convert fabric projects into quilt projects without needing to re-implement the whole QMJ spec

2024-08-10 12:06 UTC, AlexIIL requested changes
I'm somewhat conflicted about this - I agree that this functionality is useful (and needed), but unhappy about adding apis to internal packages. I can understand that there isn't really a better place for this though - it's only intended to be used by external tools that will already have to use internal code like `org.quiltmc.loader.impl.metadata.FabricModMetadataReader` and some related classes.

Overall the code is reasonable, with a couple of major problems:

- Reflection shouldn't be used to access specific fields or classes inside the same project - especially if access can be made package-private. Alternately the `getIcon` method could be made optional methods in `InternalModMetadata`, `Icons`, and `FabricLoaderModMetadata`.
- Version ranges as arrays are deprecated by the QMJ spec, in preference of explicit all/any specifiers. I've included some code which hopefully fixes this?

2024-08-10 12:06 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/InternalModMetadataJsonWriter.java
> +					return object(obj -> map.forEach((size, icon) -> obj.put(Integer.toString(size), string(icon))));
You should change these fields to package-private, rather than using reflection.

2024-08-10 12:06 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/InternalModMetadataJsonWriter.java
> +		});
Just use a `LinkedHashMap` here - it will have the same effect, without needing to write a custom comparator.

2024-08-10 12:06 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/InternalModMetadataJsonWriter.java
> +				}
You should change these fields to public rather than using reflection.

(We could debate about if we *should* expose these, considering those objects are `LEGACY_EXPOSED`, but there's no cleaner way to expose this inside the same project, and it's unlikely for quilt mods to depend on being able to access *fabric* mod internals).

2024-08-10 12:06 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/InternalModMetadataJsonWriter.java
> +		return array(range.convertToConstraints().stream().map(VersionConstraint::toString).map(InternalModMetadataJsonWriter::string));
It shouldn't be possible to convert a version range to a single array of version constraints - so I think `VersionRangeImpl.convertToConstraints()` is actually bugged.

This should also serialize using the new `object` format rather than arrays - as arrays will cause quilt loader to emit a deprecation warning. The resultant object would look like this for a VersionRange composed of 2 VersionIntervals:

```json
{
  "any": [ { "all": [ *array-1* ] }, { "all": [ *array-2* ] } ]
}
```

Using something like this code:

```java
LoaderValue writeRange(VersionRange range) {
  if (range.size() == 1) {
    VersionInterval interval = range.get(0);
    if (interval.equals(VersionInterval.ALL) {
      return string("*");
    }
    return writeInterval(interval);
  }

  List<LoaderValue> sub = new ArrayList<>();
  for (VersionInterval interval : range) {
    sub.add(writeInterval(interval));
  }

  Map<String, LoaderValue> map = new LinkedHashMap<>();
  map.put("any", array(sub));
  return object(map);
}

LoaderValue writeInterval(VersionInterval interval) {
  VersionRange createdRange = VersionRange.of(interval);
  // Convert to constraints will be accurate if there's only a single interval
  List<LoaderValue> out = new ArrayList<>();
  for (VersionConstraint constraint : createdRange.convertToConstraints()) {
    out.add(string(constraint.toString()));
  }

  if (out.size() == 1) {
    return out.get(0);
  } else {
    Map<String, LoaderValue> sub = new LinkedHashMap<>();
    sub.put("all", array(out));
    return object(sub);
  }
}
```

2024-08-10 12:06 UTC, AlexIIL commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/InternalModMetadataJsonWriter.java
> +	}
In theory it could be cleaner to use `org.quiltmc.loader.api.plugin.LoaderValueFactory` here, but the rest of the codebase doesn't :/

(Oh, and `JsonLoaderFactoryImpl.object` uses a `HashMap` rather than a `LinkedHashMap` so that would need to be changed before it could be used)

2024-08-11 04:09 UTC, OroArmor commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/InternalModMetadataJsonWriter.java
> +		return array(range.convertToConstraints().stream().map(VersionConstraint::toString).map(InternalModMetadataJsonWriter::string));
Didn't break after making it compile!

2024-08-11 04:13 UTC, OroArmor commented on src/main/java/org/quiltmc/loader/impl/metadata/qmj/InternalModMetadataJsonWriter.java
> +	}
I migrated what i could into the methods to make it use less reimplementation, but there was some stuff I couldn't change without larger changes to loader value factory.

2024-08-11 04:18 UTC, OroArmor commented
> I'm somewhat conflicted about this - I agree that this functionality is useful (and needed), but unhappy about adding apis to internal packages. I can understand that there isn't really a better place for this though - it's only intended to be used by external tools that will already have to use internal code like `org.quiltmc.loader.impl.metadata.FabricModMetadataReader` and some related classes.

Yeah that's the problem. It both needs to be "API" but also not. It *probably* wont get run when loader is actually running, its just something that a tool can use when compiled against loader.

2024-08-13 18:58 UTC, AlexIIL approved these changes

2024-08-29 15:12 UTC, closed without merging